# kustomization.yaml
resources:
  - crds.yaml       # Install CRDs first
  - common.yaml     # Common configuration second
  - operator.yaml   # Deploy the operator
  - csi-operator.yaml # Deploy CSI operator
  - cluster.yaml    # Deploy the Ceph cluster
  - toolbox.yaml    # Deploy the toolbox
  - filesystem.yaml # Deploy the filesystem
  - dashboard-external-https.yaml # Deploy the dashboard